name: py35
dependencies:
- pip=8.1.1=py35_0
- python=3.5.1=0
- setuptools=20.3=py35_0
- xz=5.0.5=1
- zlib=1.2.8=0
- pip:
  # Sphinx 1.5a0 fork w/ PRs #2431 and #2432 merged
  - git+https://github.com/agronholm/sphinx.git
  - sphinx-autodoc-typehints>=1.0.5
  - sphinxcontrib-asyncio>=0.2.0
  - /home/docs/checkouts/readthedocs.org/user_builds/asphalt/checkouts/latest
