[build-system]
requires = [
    "setuptools >= 61",
    "setuptools_scm >= 6.4"
]
build-backend = "setuptools.build_meta"

[project]
name = "asphalt"
description = "A microframework for network oriented applications"
readme = "README.rst"
authors = [{name = "Alex GrÃ¶nholm", email = "alex.gronholm@nextday.fi"}]
license = {text = "Apache License 2.0"}
classifiers = [
    "Development Status :: 5 - Production/Stable",
    "Intended Audience :: Developers",
    "License :: OSI Approved :: Apache Software License",
    "Topic :: Software Development :: Libraries :: Application Frameworks",
    "Framework :: AsyncIO",
    "Programming Language :: Python",
    "Programming Language :: Python :: 3 :: Only",
    "Programming Language :: Python :: 3.7",
    "Programming Language :: Python :: 3.8",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
]
requires-python = ">=3.7"
dependencies = [
    "importlib_metadata >= 4.4; python_version < '3.10'",
    "typing_extensions; python_version < '3.10'",
    "ruamel.yaml >= 0.15",
    "typeguard ~= 2.0",
    "async-generator ~= 1.4",
    "asyncio_extras ~= 1.3",
    "async_timeout >= 2.0",
    "click >= 6.6",
]
dynamic = ["version"]

[project.urls]
"Component projects" = "https://github.com/asphalt-framework"
Documentation = "https://asphalt.readthedocs.org/en/latest/"
"Help and support" = "https://github.com/asphalt-framework/asphalt/wiki/Help-and-support"
"Source code" = "https://github.com/asphalt-framework/asphalt"
"Issue tracker" = "https://github.com/asphalt-framework/asphalt/issues"

[project.optional-dependencies]
uvloop = ["uvloop >= 0.4.10"]
tokio = ["tokio"]
test = [
    "pytest >= 3.9",
    "pytest-asyncio",
    "pytest-cov",
    "uvloop; python_version < '3.11' and python_implementation == 'CPython' and platform_system != 'Windows'",
]
doc = [
    "Sphinx >= 1.5",
    "sphinx_rtd_theme",
    "sphinx-autodoc-typehints >= 1.2.0",
    "sphinxcontrib-asyncio >= 0.2.0",
]

[project.entry-points."asphalt.core.event_loop_policies"]
uvloop = "uvloop:EventLoopPolicy"
tokio = "tokio:TokioLoopPolicy"

[project.scripts]
asphalt = "asphalt.core.cli:main"

[tool.setuptools_scm]
version_scheme = "post-release"
local_scheme = "dirty-tag"

[tool.isort]
skip_gitignore = true
profile = "black"

[tool.flake8]
max-line-length = 99

[tool.pytest.ini_options]
addopts = "-rsx --tb=short"
asyncio_mode = "strict"
testpaths = ["tests"]

[tool.mypy]
python_version = "3.8"
show_error_codes = true

[tool.coverage.run]
source = ["asphalt"]
relative_files = true
branch = true

[tool.coverage.report]
show_missing = true

[tool.tox]
legacy_tox_ini = """
[tox]
envlist = py37, py38, py39, py310, py311, pypy3
skip_missing_interpreters = true
isolated_build = true

[testenv]
extras = test
commands = python -m pytest {posargs}

[testenv:docs]
extras = doc
commands = sphinx-build docs build/sphinx {posargs}
"""
